name: Utilities
version: 1.0
main: millen.Main
author: Millen
description: A comprehensive utilities plugin for the server

commands:
  utilreload:
    description: Reload the plugin configuration
    usage: /utilreload
    permission: utilities.reload

  heal:
    description: Heal yourself or another player
    usage: /heal [player]

  fix:
    description: Repair the item in your hand
    usage: /fix
    aliases: [repair, fixhand, fixitem]

  fixall:
    description: Repair all items in your inventory
    usage: /fixall

  ping:
    description: Check your connection ping
    usage: /ping

  feed:
    description: Restore your hunger
    usage: /feed

  announce:
    description: Send a message to all players
    usage: /announce <message>

  serverinfo:
    description: Display server information
    usage: /serverinfo
